name: gaussian_splatting_pup
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.8
  - pip
  - pytorch=2.4.1
  - torchvision=0.19.1
  - tqdm
  - pip:
    - submodules/compress-diff-gaussian-rasterization
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/rasterization_and_pup_fisher
